import Head from 'next/head'
import Homepage2 from '../components/Homepage2'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="App">
          <header className="App-header">
            <Homepage2 />
          </header>
        </div>
      </main>
    </>
  )
}
